[setup_common]
CompanyName = Mettler-Toledo (Schweiz) GmbH
ProductName = METTLER TOLEDO USB Serial Port Driver
ProductVersion = 1.34.0.4
DefaultInstDir = METTLER TOLEDO\Generic USB Serial Port Driver
SetupRegPath = METTLER TOLEDO\Generic USB Serial Port Driver\DriverSetup
CopyFiles = license_english.txt
ShowLicenseText = 1
UseCustomizedBitmap = 1
CertificateFile = vendor.cer

[setup_x86.package_1]
SupportedOS = 7, 8, 8.1
CopyFiles_1 = WdfCoInstaller01011.dll, mt_generic_usb_serial.cat, mt_generic_usb_serial.sys
PnPDriverInf_1 = mt_generic_usb_serial.inf
SubDir_1 = W7W8_x86
CheckCodeIntegrity_1 = mt_generic_usb_serial.sys

[setup_x64.package_1]
SupportedOS = 7, Server2008R2, HomeServer2011, 8, Server2012, 8.1, Server2012R2
CopyFiles_1 = WdfCoInstaller01011.dll, mt_generic_usb_serial.cat, mt_generic_usb_serial.sys
PnPDriverInf_1 = mt_generic_usb_serial.inf
SubDir_1 = W7W8_x64
CheckCodeIntegrity_1 = mt_generic_usb_serial.sys

[setup_x86.package_2]
SupportedOS = 10
CopyFiles_1 = mt_generic_usb_serial.cat, mt_generic_usb_serial.sys
PnPDriverInf_1 = mt_generic_usb_serial.inf
SubDir_1 = W10_x86
CheckCodeIntegrity_1 = mt_generic_usb_serial.sys

[setup_x64.package_2]
SupportedOS = 10, Server2016
CopyFiles_1 = mt_generic_usb_serial.cat, mt_generic_usb_serial.sys
PnPDriverInf_1 = mt_generic_usb_serial.inf
SubDir_1 = W10_x64
CheckCodeIntegrity_1 = mt_generic_usb_serial.sys

